window.CALIFICACIONES_IA = {
    "ACOSTA - RUIZ SAMANTHA": { score: 8.2, url: "https://new.misprofesores.com/profesores/Samantha-Acosta-Ruiz_189522" },
    "AGUILAR - LOZADA GABRIELA": { score: 4.3, url: "https://www.misprofesores.com/profesores/Gabriela-Aguilar-Lozada_118049" },
    "AGUILAR - RICO ADOLFO": { score: 3.5, url: "https://www.misprofesores.com/profesores/Adolfo-Aguilar-Rico_118626" },
    "AGUIRRE - SAGAON FERNANDO DANIEL": { score: 4.6, url: "https://www.misprofesores.com/profesores/Arturo-Aguirre_44010" },
    "ALCARAZ - BARRIOS MARISOL": { score: 9.3, url: "https://www.misprofesores.com/profesores/Marisol-Alcaraz-Barrios_109712" },
    "ALTAMIRANO - ROBLES LUIS CARLOS": { score: 4.9, url: "https://www.misprofesores.com/profesores/Luis-Carlos-Altamirano-Robles_22717" },
    "ARCHUNDIA - SIERRA ETELVINA": { score: 6.9, url: "https://www.misprofesores.com/profesores/Etelvina-Archundia-Sierra_36052" },
    "ARENAS - MARTINEZ GUADALUPE YOANNA": { score: 7.8, url: "https://www.misprofesores.com/profesores/Guadalupe-Yoanna-Arenas-Martinez_185131" },
    "ARIZA - VELAZQUEZ EDUARDO": { score: 6.3, url: "https://www.misprofesores.com/profesores/EDUARDO-ARIZA-VELAZQUEZ_29715" },
    "ATONAL - RAMIREZ AYDE": { score: 10.0, url: "https://www.misprofesores.com/profesores/AYDE-ATONAL-RAMIREZ_112770" },
    "AYAQUICA - MARTINEZ IRENE OLAYA": { score: 5.8, url: "https://www.misprofesores.com/profesores/Irene-Olaya-Ayaquica-Martinez_39244" },
    "BARRIOS - GONZALEZ ERICK": { score: 3.8, url: "https://www.misprofesores.com/profesores/Erick-Barrios-Gonzalez_174145" },
    "BAUTISTA - LOPEZ VERONICA EDITH": { score: 4.7, url: "https://www.misprofesores.com/profesores/Veronica-Bautista-Lopez_23875" },
    "BAUTISTA - RAMOS CESAR": { score: 8.3, url: "https://www.misprofesores.com/profesores/Cesar-Bautista-Ramos_14732" },
    "BELLO - LOPEZ PEDRO": { score: 7.6, url: "https://www.misprofesores.com/profesores/Pedro-Bello-Lopez_16887" },
    "BELTRAN - MARTINEZ BEATRIZ": { score: 8.3, url: null },
    "BERNABE - LORANCA MARIA BEATRIZ": { score: 5.6, url: "https://www.misprofesores.com/profesores/Maria-Beatriz-Bernabe-Loranca_71410" },
    "BLANCO - PEREZ GUADALUPE": { score: 0.0, url: "https://www.misprofesores.com/profesores/Guadalupe-Blanco-Perez_165282" },
    "BONFIL - BARRAGAN ERIKA": { score: 5.0, url: "https://www.misprofesores.com/profesores/Erika-Bonfil-Barragan_159490" },
    "CABRERA - CRUZ LUIS ALEJANDRO": { score: 4.4, url: "https://www.misprofesores.com/profesores/Luis-Fernando-Aceves-Cabrera_146920" },
    "CAMACHO - TELLEZ HUGO": { score: 7.5, url: "https://www.misprofesores.com/profesores/Hugo-Camacho-Tellez_158807" },
    "CARBALLIDO - CARRANZA JOSE LUIS": { score: 8.2, url: null },
    "CARREON - DIAZ DE LEON CARLOS LEOPOLDO": { score: 7.6, url: null },
    "CARRILLO - RUIZ MAYA": { score: 5.8, url: "https://www.misprofesores.com/profesores/Maya-Carrillo-Ruiz_39245" },
    "CASTILLO - AVILA ARLEM ALEIDA": { score: 9.2, url: "https://www.misprofesores.com/profesores/Arlem-Aleida-Castillo-Avila_171921" },
    "CASTILLO - ZACATELCO HILDA": { score: 8.4, url: "https://www.misprofesores.com/profesores/Hilda-Castillo-Zacatelco_16879" },
    "CERON - GARNICA CARMEN": { score: 4.6, url: "https://www.misprofesores.com/profesores/Carmen-Ceron-Garnica_25570" },
    "CHAVEZ - HEREDIA CLAUDIA": { score: 5.0, url: "https://www.misprofesores.com/profesores/Claudia-Chavez-Heredia_139300" },
    "CHAVIRA - MARTINEZ ELSA": { score: 3.4, url: "https://www.misprofesores.com/profesores/Elsa-Chavira-Martinez_48650" },
    "CHOLULA - CORDERO MARIA DE LOS ANGELES VIRGINIA": { score: 10.0, url: "https://www.misprofesores.com/profesores/MARIA-DE-LOS-ANGELES-VIRGINIA-CHOLULA-CORDERO_39419" },
    "COLMENARES - GUILLEN LUIS ENRIQUE": { score: 5.5, url: "https://www.misprofesores.com/profesores/Luis-Enrique-Colmenares-Guillen_16891" },
    "COLORADO - JIMENEZ GUILLERMO": { score: 8.3, url: "https://www.misprofesores.com/profesores/Guillermo-Colorado-Jimenez_186022" },
    "CONDE - RAMIREZ JUAN CARLOS": { score: 9.1, url: "https://www.misprofesores.com/profesores/Juan-Carlos-Conde-Ramirez_64672" },
    "CONTRERAS - GONZALEZ MELIZA": { score: 8.6, url: "https://www.misprofesores.com/profesores/Meliza-Contreras_35109" },
    "CONTRERAS - JUAREZ ROBERTO": { score: 6.7, url: "https://www.misprofesores.com/profesores/Roberto-Contreras-Juarez_16882" },
    "CONTRERAS - MONSALVO JOSE FERNANDO": { score: 7.5, url: null },
    "CORDERO - GAMBOA JUAN ROBERTO": { score: 7.5, url: "https://www.misprofesores.com/profesores/Laura-Cordero-Gamboa_136930" },
    "CORONA - MEZA WILFRIDO": { score: 0.0, url: "https://new.misprofesores.com/profesores/jose-alfredo-corona-trueba_140640" },
    "CORONA - REYES ADRIANA ISABEL": { score: 9.0, url: "https://www.misprofesores.com/profesores/ADRIANA-ISABEL-CORONA-REYES_154807" },
    "CORONA - SANCHEZ ESTEBAN": { score: 8.0, url: null },
    "CORTES - VAZQUEZ EDMUNDO MIGUEL": { score: 4.0, url: "https://www.misprofesores.com/profesores/Edmundo-Miguel-Cortes-Vazquez_194917" },
    "CORTES - VAZQUEZ MARIBEL": { score: 7.0, url: "https://www.misprofesores.com/profesores/Maribel-Cortes_106825" },
    "CORTEZ - . ERNEST": { score: 7.9, url: "https://www.misprofesores.com/profesores/Ernest-Cortez_176579" },
    "CRUZ - ALMANZA GRACIANO": { score: 6.5, url: "https://www.misprofesores.com/profesores/Graciano-Cruz-Almanza_27353" },
    "CUATZO - TONACATL GLORIA": { score: 6.0, url: "https://www.misprofesores.com/profesores/Gloria-Cuatzo-Tonacatl_189518" },
    "CUAYAHUITL - ROMERO LAURA": { score: 6.5, url: "https://www.misprofesores.com/profesores/Laura-Cuayahuitl-Romero_21685" },
    "DE ITA - LUNA DANIEL": { score: 2.0, url: "https://www.misprofesores.com/profesores/Daniel-De-Ita_185122" },
    "DE ITA - LUNA GUILLERMO": { score: 5.1, url: "https://www.misprofesores.com/profesores/Guillermo-De-Ita-Luna_43965?pag=1" },
    "DE LA ROSA - FLORES RAFAEL": { score: 3.6, url: "https://www.misprofesores.com/profesores/RAFAEL-DE-LA-ROSA-FLORES_102656" },
    "DE PEDRO - CORONA ANACLETO": { score: 7.9, url: null },
    "DEL ROSARIO - HUITZIL RICARDO": { score: 6.8, url: "https://www.misprofesores.com/profesores/Ricardo-Del-Rosario-Huitzil_125653" },
    "ELVIRA - ENRIQUEZ ROBERTO": { score: 9.2, url: "https://www.misprofesores.com/profesores/Roberto-Elvira-Enriquez_135940" },
    "ESPINDOLA - POZOS ARMANDO": { score: 8.5, url: "https://www.misprofesores.com/profesores/ARMANDO-ESPINDOLA-POZOS_36266" },
    "ESPINOZA - HERNANDEZ NELVA BETZABEL": { score: 9.4, url: "https://www.misprofesores.com/profesores/NELVA-BETZABEL-ESPINOZA-HERNANDEZ_29860" },
    "FLORES - CALYECA CARINA": { score: 10.0, url: "https://www.misprofesores.com/profesores/Carina-Flores-Calyeca_109554" },
    "FLORES - FLORES JOSE LUIS": { score: 8.2, url: null },
    "GALICIA - HERNANDEZ YALU": { score: 6.5, url: "https://www.misprofesores.com/profesores/Yalu-Galicia-Hernandez_16892" },
    "GARCIA - ALONSO MARCELA": { score: 10.0, url: "https://www.misprofesores.com/profesores/Marcela-Alonso-Garcia_172230" },
    "GARCIA - JUAREZ PEDRO": { score: 7.8, url: "https://www.misprofesores.com/profesores/pedro-Garcia-juarez_69998" },
    "GARCIA - LOPEZ MARGARITA CARMINA": { score: 5.8, url: null },
    "GARCIA - TAMAYO ROSA": { score: 6.7, url: "https://www.misprofesores.com/profesores/Rosa-Garcia-Tamayo_44319" },
    "GOMEZ - TRUJILLO ALONSO ERICK": { score: 9.3, url: "https://www.misprofesores.com/profesores/Angelica-Trujillo-Hernandez_59145" },
    "GONZALEZ - ARRIAGA DANIEL MARCELO": { score: 6.0, url: "https://www.misprofesores.com/profesores/Daniel-Marcelo-Gonzalez-Arriaga_167738" },
    "GONZALEZ - CALLEROS JUAN MANUEL": { score: 7.1, url: "https://www.misprofesores.com/profesores/Juan-Manuel-Gonzalez-Calleros_40246" },
    "GONZALEZ - FLORES MARCOS": { score: 6.7, url: "https://www.misprofesores.com/profesores/Marcos-Gonzalez-Flores_20693" },
    "GONZALEZ - VELAZQUEZ ROGELIO": { score: 7.6, url: "https://www.misprofesores.com/profesores/Rogelio-Gonzalez-Velazquez_16893" },
    "GUERRERO - GARCIA JOSEFINA": { score: 8.2, url: "https://www.misprofesores.com/profesores/Josefina-Guerrero-Garcia_40245" },
    "HERNANDEZ - ADRIANO GUADALUPE DANIEL": { score: 8.5, url: null },
    "HERNANDEZ - AMECA JOSE LUIS": { score: 6.6, url: "https://www.misprofesores.com/profesores/Jose-Luis-Hernandez-Ameca_23870" },
    "HERNANDEZ - BERISTAIN ADRIANA": { score: 7.0, url: null },
    "HERNANDEZ - GRACIDA MARIO OLMOS": { score: 7.0, url: null },
    "HERNANDEZ - HERNANDEZ MARIA DEL ROSARIO": { score: 7.3, url: "https://www.misprofesores.com/profesores/Maria-del-Rosario-Hernandez-Hernandez_16881" },
    "HERNANDEZ - RAMIREZ ANABEL": { score: 0.0, url: "https://www.misprofesores.com/profesores/Anabel-Hernandez-Ramirez_171896" },
    "HURTADO - MADRID JOSE MIGUEL": { score: 0.0, url: "https://www.misprofesores.com/profesores/Jose-Miguel-Hurtado-Madrid_169262" },
    "JIMENEZ - DE LOS SANTOS GUILLERMO": { score: 4.3, url: "https://www.misprofesores.com/profesores/Guillermo-Jimenez-de-los-Santos_153207" },
    "JIMENEZ - SANCHEZ ANETTE ESMERALDA": { score: 6.0, url: "https://www.misprofesores.com/profesores/Anette-Esmeralda-Jimenez-Sanchez_137946" },
    "LARIOS - GOMEZ MARIANO": { score: 7.4, url: "https://www.misprofesores.com/profesores/Mariano-Larios-Gomez_23876" },
    "LAVALLE - MARTINEZ JOSE DE JESUS": { score: 5.7, url: "https://www.misprofesores.com/profesores/Jose-de-Jesus-Lavalle-Martinez_16884" },
    "LEON - ALDANA GABRIELA": { score: 8.7, url: null },
    "LEYVA - BONILLA JUAN FRANCISCO": { score: 9.2, url: "https://www.misprofesores.com/profesores/Juan-Francisco-Leyva-Bonilla_99148" },
    "LEZAMA - DE JESUS VERONICA": { score: 8.9, url: "https://www.misprofesores.com/profesores/Veronica-Lezama-De-Jesus_119956" },
    "LOPEZ - MUNOZ MAURO ALBERTO": { score: 9.8, url: "https://www.misprofesores.com/profesores/Mauro-Alberto-Lopez-Munoz_178217" },
    "LOPEZ - POBLANO GILBERTO": { score: 9.3, url: "https://www.misprofesores.com/profesores/Gilberto-Lopez-Poblano_100738" },
    "LOPEZ - SOSA ZURIEL": { score: 8.6, url: "https://www.misprofesores.com/profesores/Zuriel-Lopez-Sosa_179498" },
    "LUNA - RAMIREZ JOSE ANDRES": { score: 6.8, url: null },
    "MALDONADO - GARCIA ABRAHAM": { score: 6.1, url: "https://www.misprofesores.com/profesores/Abraham-Maldonado-Garcia_95047" },
    "MANTILLA - NARVAEZ LILIA": { score: 9.3, url: "https://www.misprofesores.com/profesores/Lilia-Mantilla-Narvaez_37854" },
    "MARCIAL - CASTILLO LUIS RENE": { score: 7.2, url: "https://www.misprofesores.com/profesores/Luis-Rene-Marcial-Castillo_36751" },
    "MARIN - GRACIA GRACIELA": { score: 8.8, url: null },
    "MARIN - URBANO DIONISIO EDUARDO": { score: 4.8, url: "https://www.misprofesores.com/profesores/Dionisio-Marin-Urbano_113499" },
    "MARTINEZ - GUZMAN GERARDO": { score: 8.4, url: "https://www.misprofesores.com/profesores/Gerardo-Martinez-Guzman_30614" },
    "MARTINEZ - MELGAR JESSICA": { score: 4.4, url: "https://www.misprofesores.com/profesores/Jessica-Martinez-Melgar_141517" },
    "MARTINEZ - MIRON ERIKA ANNABEL": { score: 4.3, url: "https://www.misprofesores.com/profesores/ERIKA-ANNABEL-MARTINEZ-MIRON_91104" },
    "MEJIA - MATIAS HILDA": { score: 6.0, url: "https://www.misprofesores.com/profesores/Hilda-Mejia-Matias_93468" },
    "MEJIA - PALAFOX JUAN": { score: 4.4, url: "https://www.misprofesores.com/profesores/Juan-Mejia-Palafox_16885" },
    "MELENDEZ - TEODORO AUGUSTO": { score: 5.0, url: "https://www.misprofesores.com/profesores/AUGUSTO-MELENDEZ-TEODORO_159517" },
    "MENA - LUNA LUIS ALFREDO": { score: 10.0, url: "https://www.misprofesores.com/profesores/Luis-Fernando-Luna-Pando_171663" },
    "MENDEZ - SANCHEZ LUIS YAEL": { score: 8.8, url: "https://www.misprofesores.com/profesores/Luis-Yael-Mendez-Sanchez_166908" },
    "MENDOZA - OLGUIN GUSTAVO EMILIO": { score: 7.3, url: "https://www.misprofesores.com/profesores/Gustavo-Emilio-Mendoza-Olguin_166837" },
    "MENDOZA - ROJAS ANGEL OMAR": { score: 9.1, url: "https://www.misprofesores.com/profesores/Angel-Omar-Mendoza-Rojas_91000" },
    "MOLINA - GARCIA MARIA DEL CONSUELO": { score: 5.7, url: "https://www.misprofesores.com/profesores/Consuelo-Molina-Garcia_20654" },
    "MONTES - VALLIN TANYA VICTORIA": { score: 4.4, url: "https://new.misprofesores.com/profesores/Victoria-Perez_79983" },
    "MORALES - AGUILAR LUIS ENRIQUE": { score: 7.2, url: null },
    "MOYAO - MARTINEZ YOLANDA": { score: 7.4, url: "https://www.misprofesores.com/profesores/yolanda-moyao-martinez_18798" },
    "OIDOR - GARCIA JOSE JULIAN JUAN": { score: 4.5, url: "https://www.misprofesores.com/profesores/JOSE-OIDOR-GARCIA_97113" },
    "OLIVARES - SOTO LUIS GUSTAVO": { score: 0.0, url: "https://new.misprofesores.com/profesores/raul-avelino-olivares_33183" },
    "OLIVOS - CONTRERAS MARIA ERIKA": { score: 3.2, url: "https://www.misprofesores.com/profesores/MARIA-ERIKA-OLIVOS-CONTRERAS_184980" },
    "OLMOS - PINEDA IVAN": { score: 8.3, url: "https://www.misprofesores.com/profesores/Ivan-Olmos-Pineda_40577" },
    "OLVERA - LOPEZ JOSE ARTURO": { score: 8.1, url: "https://www.misprofesores.com/profesores/Arturo-Olvera-Lopez_30114" },
    "ORATO - RAMIREZ JOSE MARTIN": { score: 8.0, url: "https://new.misprofesores.com/profesores/Jose-Martin-Orato-Ramirez_32439" },
    "ORTEGA - VERGARA MARTHA OFELIA": { score: 8.5, url: "https://new.misprofesores.com/profesores/Blanca-Edith-Vergara-Ortega_30653" },
    "OSUNA - GONZALEZ REYNOLD": { score: 9.0, url: "https://www.misprofesores.com/profesores/Reynold-Osuna-Gonzalez_171338" },
    "OTERO - GONZALEZ JORGE": { score: 8.0, url: "https://www.misprofesores.com/profesores/Jorge-Otero-Gonzalez_188866" },
    "PALOMINO - JIMENEZ CARLOS": { score: 8.5, url: null },
    "PEREZ - LUCERO JOSUE": { score: 8.6, url: "https://www.misprofesores.com/profesores/Josue-Perez-Lucero_78085" },
    "PEREZ - PEREZ FABRICIO OTONIEL": { score: 6.9, url: "https://www.misprofesores.com/profesores/Fabricio-Otoniel-Perez-Perez_175218" },
    "PEREZ - PEREZ JOSE CARLOS": { score: 8.1, url: null },
    "PEREZ DE CELIS - HERRERO MARIA DE LA CONCEPCION": { score: 6.0, url: "https://www.misprofesores.com/profesores/maria-de-la-concepcion-perez-de-celis-herrero_154612" },
    "PIANTZI - VARELA LETICIA": { score: 8.7, url: "https://www.misprofesores.com/profesores/Leticia-Piantzi-Varela_119968" },
    "PORTILLO - RAMIREZ GUSTAVO": { score: 9.7, url: "https://new.misprofesores.com/profesores/Gustavo-Portillo-Ramirez_189907" },
    "RAMIREZ - DIAZ MARIO ANIBAL": { score: 7.4, url: null },
    "RAMIREZ - ESPITIA CARLOS MAURICIO": { score: 6.9, url: "https://www.misprofesores.com/profesores/Carlos-Mauricio-Ramirez-Espitia_55569" },
    "RAMIREZ - HERNANDEZ HECTOR DAVID": { score: 9.3, url: "https://www.misprofesores.com/profesores/Hector-David-Ramirez-Hernandez_154640" },
    "REGINO - MEDINA LUIS FILIBERTO": { score: 8.0, url: "https://www.misprofesores.com/profesores/Luis-Filiberto-Regino-Medina_194354" },
    "REYES - GARCES LUZ DEL CARMEN": { score: 6.5, url: "https://www.misprofesores.com/profesores/Luz-del-Carmen-Reyes-Garces_64192" },
    "RIOS - GONZALEZ ELVIA": { score: 7.7, url: "https://www.misprofesores.com/profesores/Elvia-Rios-Gonzalez_180698" },
    "RIVERA - JIMENEZ CONCEPCION CRISTAL": { score: 8.4, url: "https://www.misprofesores.com/profesores/Dolores-judith-Caballero-jimenez_187960" },
    "RIVERA - MARTINEZ MARCELA": { score: 5.4, url: "https://www.misprofesores.com/profesores/Marcela-Rivera-Martinez_22414" },
    "RIVERA - ZURITA ABRIL LUCIA": { score: 5.8, url: "https://www.misprofesores.com/profesores/Abril-Lucia-Rivera-Zurita_184160" },
    "ROBLES - MENDOZA FRANCISCO JAVIER": { score: 6.5, url: null },
    "RODRIGUEZ - BERNAL FERNANDO": { score: 7.8, url: null },
    "RODRIGUEZ - PEDROZA BERENICE": { score: 9.8, url: "https://www.misprofesores.com/profesores/Berenice-Rodriguez-Pedroza_158805?pag=2" },
    "RODRIGUEZ - PEREZ FERNANDO": { score: 5.2, url: "https://www.misprofesores.com/profesores/FERNANDO-RODRIGUEZ-PEREZ_50619" },
    "ROJAS - PEREZ ISRRAEL": { score: 5.1, url: "https://www.misprofesores.com/profesores/ISRRAEL-ROJAS-PEREZ_86853" },
    "ROJAS - RIVERA IVAN": { score: 5.5, url: "https://www.misprofesores.com/profesores/ignacio-rojas_17150?pag=0" },
    "ROJAS - TLELO CARMEN": { score: 8.6, url: null },
    "ROMAN - FLORES ALBERTO": { score: 7.8, url: "https://www.misprofesores.com/profesores/ALBERTO-ROMAN-FLORES_74070" },
    "ROMERO - HERNANDEZ YEINY": { score: 7.5, url: "https://www.misprofesores.com/profesores/Yeiny-Romero-Hernandez_102696" },
    "ROMERO - SIERRA JAIME ALEJANDRO": { score: 8.2, url: "https://www.misprofesores.com/profesores/Jaime-Alejandro-Romero-Sierra_184254" },
    "ROMERO - TEHUITZIL OLIVIA": { score: 8.5, url: "https://www.misprofesores.com/profesores/Olivia-Romero-Tehuitzil_22563" },
    "ROMERO - VALDEZ MARIA DEL CARMEN": { score: 9.2, url: "https://www.misprofesores.com/profesores/Maria-del-Carmen-Romero-Valdez_119617" },
    "ROSALES - LOPEZ KARINA": { score: 6.0, url: "https://www.misprofesores.com/profesores/Karina-Rosales-Lopez_72868" },
    "ROSSAINZ - LOPEZ MARIO": { score: 7.7, url: "https://www.misprofesores.com/profesores/Mario-Rossainz-Lopez_16895" },
    "RUBIN - LINARES GUSTAVO TRINIDAD": { score: 3.6, url: "https://www.misprofesores.com/profesores/GUSTAVO-RUBIN-LINARES_25944" },
    "RUIZ - DIAZ MARIA ANTONIA": { score: 8.9, url: "https://www.misprofesores.com/profesores/Maria-Antonia-Ruiz-Diaz_82722" },
    "SALAS - GUEVARA MONICA YISSEL": { score: 10.0, url: "https://new.misprofesores.com/profesores/Monica-Guevara-Rojo_64758" },
    "SALAZAR - PEDRAZA MARIA MONTSERRAT": { score: 8.0, url: "https://www.misprofesores.com/profesores/maria-teresa-salazar-pena_33602" },
    "SANCHEZ - GALVEZ MARIA EUGENIA NARCIZA SULLY": { score: 3.9, url: "https://www.misprofesores.com/profesores/Maria-Eugenia-Narcisa-Sully-Sanchez-Galvez_36752" },
    "SANCHEZ - LOPEZ ABRAHAM": { score: 5.5, url: "https://www.misprofesores.com/profesores/Abraham-Sanchez-Lopez_16886" },
    "SANCHEZ - RODRIGUEZ EVA MARIA": { score: 9.3, url: "https://www.misprofesores.com/profesores/jose-luis-rodriguez-sanchez_25556" },
    "SANCHEZ - ROMAN GUILLERMINA": { score: 4.8, url: "https://www.misprofesores.com/profesores/Guillermina-Sanchez-Roman_44803" },
    "SILVA - SANCHEZ PATRICIA": { score: 7.5, url: "https://www.misprofesores.com/profesores/Patricia-Silva-Sanchez_98858" },
    "SORIANO - ROSAS JOSE ISABEL": { score: 4.4, url: "https://www.misprofesores.com/profesores/Jose-Isabel-Soriano-Rosas_159455" },
    "TECUANHUEHUE - VERA PEDRO": { score: 6.1, url: "https://www.misprofesores.com/profesores/Pedro-Tecuanhuehue-Vera_157555" },
    "TECUATL - CUAUTLE ARACELI": { score: 10.0, url: "https://www.misprofesores.com/profesores/Araceli-Tecuatl-Cuautle_166878" },
    "TOBON - LEON BEATRIZ": { score: 5.8, url: "https://www.misprofesores.com/profesores/Maria-de-Jesus-Tobon-Ramirez_97472" },
    "TORIZ - PALACIOS ALFREDO": { score: 6.9, url: "https://www.misprofesores.com/profesores/Alfredo-Toriz-Palacios_56562" },
    "TORRES - ACUITLAPA OMAR": { score: 3.7, url: "https://www.misprofesores.com/profesores/Omar-Torres-Acuitlapa_85710" },
    "TORRES - GONZALEZ MAURICIO": { score: 10.0, url: "https://www.misprofesores.com/profesores/JUAN-MAURICIO-TORRES-GONZALEZ_171763" },
    "TORRIJOS - MUNOZ MARIA TERESA": { score: 3.7, url: "https://www.misprofesores.com/profesores/Maria-Teresa-Torrijos-Munoz_64801" },
    "TOVAR - VIDAL MIREYA": { score: 6.2, url: "https://www.misprofesores.com/profesores/MIREYA-TOVAR-VIDAL_36262" },
    "TREVINO - SANCHEZ DANIEL": { score: 0.0, url: "https://www.misprofesores.com/profesores/Daniel-Trevino-Sanchez_99707" },
    "TRINIDAD - GARCIA GREGORIO": { score: 5.2, url: "https://www.misprofesores.com/profesores/GREGORIO-TRINIDAD-GARCIA_30722" },
    "VALDES - AMARO DANIEL ALEJANDRO": { score: 6.2, url: "https://www.misprofesores.com/profesores/daniel-alejandro-valdes-amaro_49115" },
    "VALENCIA - SEGURA LUIS ERNESTO": { score: 5.8, url: "https://www.misprofesores.com/profesores/Luis-Ernesto-Valencia-Segura_174635" },
    "VARGAS - CORTEZ LUIS IGNACIO": { score: 7.5, url: null },
    "VARGAS - LOMELI MIGUEL ANGEL": { score: 8.3, url: "https://www.misprofesores.com/profesores/Miguel-Angel-Vargas-Lomeli_97744" },
    "VAZQUEZ - RAMIREZ JESUS": { score: 4.9, url: "https://www.misprofesores.com/profesores/Jesus-Vazquez-Ramirez_34822" },
    "VELAZQUEZ - LEON PEDRO": { score: 8.0, url: null },
    "VERA - CERVANTES EUGENIA ERICA": { score: 4.3, url: "https://www.misprofesores.com/profesores/Maria-Erika-Eugenia-Vera-Cervantes_17428" },
    "VILARINO - AYALA DARNES": { score: 7.6, url: "https://www.misprofesores.com/profesores/Darnes-Vilarino-Ayala_15695" },
    "ZACARIAS - FLORES FERNANDO": { score: 6.9, url: "https://www.misprofesores.com/profesores/Fernado-Zacarias-Flores_38465" },
    "ZAMORA - LIMA CARLOS": { score: 9.5, url: "https://www.misprofesores.com/profesores/ZAMORA-LIMA-CARLOS_37947" },
    "ZEPEDA - CORTES CLAUDIA": { score: 7.9, url: "https://www.misprofesores.com/profesores/Claudia-Zepeda-Cortes_37932?pag=6" },
    "ZUNIGA - LOPEZ JAZMIN": { score: 9.5, url: "https://www.misprofesores.com/profesores/Jazmin-Zuniga-Lopez_179371" }
};
